### ISSUE TITLE
/docker-entrypoint.sh: 11: exec: ./PalServer.sh: not found

### ISSUE THREAD

**Issue by Zxeao** [moefaq/palworld-dedicated-server#2]
palworld-dedicated-server_1 | Connecting anonymously to Steam Public...OK
palworld-dedicated-server_1 | Waiting for client config...OK
palworld-dedicated-server_1 | Waiting for user info...OK
palworld-dedicated-server_1 |  Update state (0x0) : Timed out waiting for update to start, bailing.
palworld-dedicated-server_1 | Error! App '2394010' state is 0x202 after update job.
palworld-dedicated-server_1 | Running Options:
palworld-dedicated-server_1 | /docker-entrypoint.sh: 11: exec: ./PalServer.sh: not found
palworld-dedicated-server_1 exited with code 127

**Comment by moefaq** [comment]
```
Error 0x202
Not enough disk space.
```
检查磁盘剩余空间。
